name: Save AWS CodeArtifact Secret

on:
  push:
    branches:
      - main
  schedule:
    - cron: "50 */7 * * *"  # Runs every 7 hours at 50 minutes past the hour
  workflow_dispatch:  # Allows manual triggering

permissions:
  id-token: write
  contents: read

jobs:
  save-codeartifact-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1  # Replace with your AWS region if different

      - name: Get CodeArtifact token
        id: get-token
        run: |
          TOKEN=$(aws codeartifact get-authorization-token \
            --domain hariapsh \
            --domain-owner 412843963500 \
            --query authorizationToken \
            --output text)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Save Token as Dependabot Secret
        env:
          GH_TOKEN: ${{ secrets.AWS_CODEARTIFACT_TOKEN_REFRESH_GH_PAT }}
        run: |
          gh secret set AWS_CODEARTIFACT_TOKEN \
            --app dependabot \
            --org hariapsh-org \
            --visibility all \
            --body "${{ steps.get-token.outputs.token }}"
