
name: Test Docker Bind Mount
on: [push]

jobs:
  test-fleet:
    runs-on:
      - codebuild-aws-shr-${{ github.run_id }}-${{ github.run_attempt }}
      fleet: bindfleet
      image: arm-3.0
    steps:
      - uses: actions/checkout@v4
      
      - name: Build test image
        run: docker build -t test-image .
      
      - name: Test bind mount (should fail in fleet)
        run: |
          echo "Testing bind mount with workspace: ${{ github.workspace }}"
          ls -la "${{ github.workspace }}"
          
          docker run --rm \
            --mount type=bind,source="${{ github.workspace }}",target=/workdir \
            -w /workdir \
            test-image \
            sh -c "
              echo '+++ Checking mounted directory'
              ls -la /workdir
              echo '+++ Looking for package.json'
              ls -la /workdir/package.json || echo 'package.json NOT FOUND'
            "

  test-ondemand:
    runs-on:
      - codebuild-aws-shr-${{ github.run_id }}-${{ github.run_attempt }}
      image: arm-3.0
    steps:
      - uses: actions/checkout@v4
      
      - name: Build test image
        run: docker build -t test-image .
      
      - name: Test bind mount (should work in on-demand)
        run: |
          echo "Testing bind mount with workspace: ${{ github.workspace }}"
          ls -la "${{ github.workspace }}"
          
          docker run --rm \
            --mount type=bind,source="${{ github.workspace }}",target=/workdir \
            -w /workdir \
            test-image \
            sh -c "
              echo '+++ Checking mounted directory'
              ls -la /workdir
              echo '+++ Looking for package.json'
              ls -la /workdir/package.json || echo 'package.json NOT FOUND'
            "
